import { Button } from "@/components/ui/button"
import { cssQuizesss, htmlQuizzes, jsQuizzes } from "@/constants/quizzes";
import { IQuiz } from "@/types";
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom"

const Home = () => {
  const navigate = useNavigate();
  const { name } = useParams();
  const [section, setSection] = useState<IQuiz[]>();

  useEffect(() => {
    switch (name) {
      case 'html':        setSection(htmlQuizzes); break
      case 'css':         setSection(cssQuizesss); break
      case 'javascript':  setSection(jsQuizzes); break
      default:            setSection([...htmlQuizzes, ...cssQuizesss, ...jsQuizzes])
    }
  }, [name]);


  return (
    <section className="container">
      <div className="flex flex-col mb-5">
        <h2 className="h2-bold">Explore and Test Your Web Development Knowledge</h2>
        <p className="base-regular w-2/3 text-neutral-400"> Welcome to our web development platform! Dive into the world of web technologies with engaging quizzes created by developers for developers. Validate your knowledge by solving captivating questions and discover something new.</p>
      </div>
      <Button variant='destructive' className="mb-5">All quizzes were generated by ChatGPT.</Button>

      <div className="h-[1px] w-full bg-neutral-800 mb-5"></div>


      <div className="flex space-x-5">
        {section?.map((quizItem) => (
          <div key={quizItem.id} className="flex flex-col justify-between border border-neutral-800 rounded-xl p-5 w-[200px] h-[180px]">
            <img src={quizItem.image} alt="" className="mb-2 h-[50px] object-contain" />
            <div className="flex flex-col">
              <p className="text-center body-bold mb-2">{quizItem.title}</p>
              <Button variant='outline' className="h-6" onClick={() => navigate(`/quiz/${quizItem.id}`)}>Start</Button>
            </div>
          </div>
        ))}

      </div>
    </section>
  )
}

export default Home